### ISSUE TITLE
Wall Broken ( Level Design)

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/TheInterview#174]
![image](https://user-images.githubusercontent.com/56066524/81867381-4639dc80-9579-11ea-8546-756534bd1cd5.png)

**Comment by mustucontractor** [comment]
![image](https://user-images.githubusercontent.com/56066524/81867548-8e58ff00-9579-11ea-97ca-24246d7e62a4.png)
this too

**Comment by SilasReinagel** [comment]
Fixed in latest unreleased build.
